language: node_js
node_js:
- "10"

before_install:
- npm i -g npm
- npm --version

script:
- sh common/project-check.sh
- npm run lint
- npm run compile-check
- npm run nsp
- npm run coverage

after_success:
- npm run upload-coverage

notifications:
  email: false
